In [3]:
import pandas as pd

In [4]:
dataset=pd.read_csv("preplacement.csv")
dataset

Unnamed: 0  sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p    salary  \
0             0    1.0  67.00  91.00     58.00     55.0  58.80  270000.0   
1             1    2.0  79.33  78.33     77.48     86.5  66.28  200000.0   
2             2    3.0  65.00  68.00     64.00     75.0  57.80  250000.0   
3             3    4.0  56.00  52.00     52.00     66.0  59.43  265000.0   
4             4    5.0  85.80  73.60     73.30     96.8  55.50  390000.0   
..          ...    ...    ...    ...       ...      ...    ...       ...   
210         210  211.0  80.60  82.00     77.60     91.0  74.49  390000.0   
211         211  212.0  58.00  60.00     72.00     74.0  53.62  275000.0   
212         212  213.0  67.00  67.00     73.00     59.0  69.72  295000.0   
213         213  214.0  74.00  66.00     58.00     70.0  60.23  204000.0   
214         214  215.0  62.00  58.00     53.00     89.0  60.22  265000.0   

    gender    ssc_b    hsc_b     hsc_s   degree_t workex specialisation  \
0        M   Others   Others  Commerce   Sci&Tech     No         Mkt&HR   
1        M  Central   Others   Science   Sci&Tech    Yes        Mkt&Fin   
2        M  Central  Central      Arts  Comm&Mgmt     No        Mkt&Fin   
3        M  Central  Central   Science   Sci&Tech     No         Mkt&HR   
4        M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin   
..     ...      ...      ...       ...        ...    ...            ...   
210      M   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin   
211      M   Others   Others   Science   Sci&Tech     No        Mkt&Fin   
212      M   Others   Others  Commerce  Comm&Mgmt    Yes        Mkt&Fin   
213      F   Others   Others  Commerce  Comm&Mgmt     No         Mkt&HR   
214      M  Central   Others   Science  Comm&Mgmt     No         Mkt&HR   

         status  
0        Placed  
1        Placed  
2        Placed  
3    Not Placed  
4        Placed  
..          ...  
210      Placed  
211      Placed  
212      Placed  
213      Placed  
214  Not Placed  

[215 rows x 16 columns]

In [5]:
dataset.drop(["sl_no","Unnamed: 0"],inplace=True,axis=1)
dataset

ssc_p  hsc_p  degree_p  etest_p  mba_p    salary gender    ssc_b  \
0    67.00  91.00     58.00     55.0  58.80  270000.0      M   Others   
1    79.33  78.33     77.48     86.5  66.28  200000.0      M  Central   
2    65.00  68.00     64.00     75.0  57.80  250000.0      M  Central   
3    56.00  52.00     52.00     66.0  59.43  265000.0      M  Central   
4    85.80  73.60     73.30     96.8  55.50  390000.0      M  Central   
..     ...    ...       ...      ...    ...       ...    ...      ...   
210  80.60  82.00     77.60     91.0  74.49  390000.0      M   Others   
211  58.00  60.00     72.00     74.0  53.62  275000.0      M   Others   
212  67.00  67.00     73.00     59.0  69.72  295000.0      M   Others   
213  74.00  66.00     58.00     70.0  60.23  204000.0      F   Others   
214  62.00  58.00     53.00     89.0  60.22  265000.0      M  Central   

       hsc_b     hsc_s   degree_t workex specialisation      status  
0     Others  Commerce   Sci&Tech     No         Mkt&HR      Placed  
1     Others   Science   Sci&Tech    Yes        Mkt&Fin      Placed  
2    Central      Arts  Comm&Mgmt     No        Mkt&Fin      Placed  
3    Central   Science   Sci&Tech     No         Mkt&HR  Not Placed  
4    Central  Commerce  Comm&Mgmt     No        Mkt&Fin      Placed  
..       ...       ...        ...    ...            ...         ...  
210   Others  Commerce  Comm&Mgmt     No        Mkt&Fin      Placed  
211   Others   Science   Sci&Tech     No        Mkt&Fin      Placed  
212   Others  Commerce  Comm&Mgmt    Yes        Mkt&Fin      Placed  
213   Others  Commerce  Comm&Mgmt     No         Mkt&HR      Placed  
214   Others   Science  Comm&Mgmt     No         Mkt&HR  Not Placed  

[215 rows x 14 columns]

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

ssc_p  hsc_p  degree_p  etest_p  mba_p    salary  gender_M  ssc_b_Others  \
0    67.00  91.00     58.00     55.0  58.80  270000.0         1             1   
1    79.33  78.33     77.48     86.5  66.28  200000.0         1             0   
2    65.00  68.00     64.00     75.0  57.80  250000.0         1             0   
3    56.00  52.00     52.00     66.0  59.43  265000.0         1             0   
4    85.80  73.60     73.30     96.8  55.50  390000.0         1             0   
..     ...    ...       ...      ...    ...       ...       ...           ...   
210  80.60  82.00     77.60     91.0  74.49  390000.0         1             1   
211  58.00  60.00     72.00     74.0  53.62  275000.0         1             1   
212  67.00  67.00     73.00     59.0  69.72  295000.0         1             1   
213  74.00  66.00     58.00     70.0  60.23  204000.0         0             1   
214  62.00  58.00     53.00     89.0  60.22  265000.0         1             0   

     hsc_b_Others  hsc_s_Commerce  hsc_s_Science  degree_t_Others  \
0               1               1              0                0   
1               1               0              1                0   
2               0               0              0                0   
3               0               0              1                0   
4               0               1              0                0   
..            ...             ...            ...              ...   
210             1               1              0                0   
211             1               0              1                0   
212             1               1              0                0   
213             1               1              0                0   
214             1               0              1                0   

     degree_t_Sci&Tech  workex_Yes  specialisation_Mkt&HR  status_Placed  
0                    1           0                      1              1  
1                    1           1                      0              1  
2                    0           0                      0              1  
3                    1           0                      1              0  
4                    0           0                      0              1  
..                 ...         ...                    ...            ...  
210                  0           0                      0              1  
211                  1           0                      0              1  
212                  0           1                      0              1  
213                  0           0                      1              1  
214                  0           0                      1              0  

[215 rows x 16 columns]

In [7]:
dataset.columns

Index(['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary', 'gender_M',
       'ssc_b_Others', 'hsc_b_Others', 'hsc_s_Commerce', 'hsc_s_Science',
       'degree_t_Others', 'degree_t_Sci&Tech', 'workex_Yes',
       'specialisation_Mkt&HR', 'status_Placed'],
      dtype='object')

In [8]:
independent=dataset[['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p','gender_M',
       'ssc_b_Others', 'hsc_b_Others', 'hsc_s_Commerce', 'hsc_s_Science',
       'degree_t_Others', 'degree_t_Sci&Tech', 'workex_Yes',
       'specialisation_Mkt&HR', 'status_Placed']]
independent

ssc_p  hsc_p  degree_p  etest_p  mba_p  gender_M  ssc_b_Others  \
0    67.00  91.00     58.00     55.0  58.80         1             1   
1    79.33  78.33     77.48     86.5  66.28         1             0   
2    65.00  68.00     64.00     75.0  57.80         1             0   
3    56.00  52.00     52.00     66.0  59.43         1             0   
4    85.80  73.60     73.30     96.8  55.50         1             0   
..     ...    ...       ...      ...    ...       ...           ...   
210  80.60  82.00     77.60     91.0  74.49         1             1   
211  58.00  60.00     72.00     74.0  53.62         1             1   
212  67.00  67.00     73.00     59.0  69.72         1             1   
213  74.00  66.00     58.00     70.0  60.23         0             1   
214  62.00  58.00     53.00     89.0  60.22         1             0   

     hsc_b_Others  hsc_s_Commerce  hsc_s_Science  degree_t_Others  \
0               1               1              0                0   
1               1               0              1                0   
2               0               0              0                0   
3               0               0              1                0   
4               0               1              0                0   
..            ...             ...            ...              ...   
210             1               1              0                0   
211             1               0              1                0   
212             1               1              0                0   
213             1               1              0                0   
214             1               0              1                0   

     degree_t_Sci&Tech  workex_Yes  specialisation_Mkt&HR  status_Placed  
0                    1           0                      1              1  
1                    1           1                      0              1  
2                    0           0                      0              1  
3                    1           0                      1              0  
4                    0           0                      0              1  
..                 ...         ...                    ...            ...  
210                  0           0                      0              1  
211                  1           0                      0              1  
212                  0           1                      0              1  
213                  0           0                      1              1  
214                  0           0                      1              0  

[215 rows x 15 columns]

In [9]:
dependent=dataset[['salary']]
dependent

salary
0    270000.0
1    200000.0
2    250000.0
3    265000.0
4    390000.0
..        ...
210  390000.0
211  275000.0
212  295000.0
213  204000.0
214  265000.0

[215 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [12]:
x_test

array([[ 3.57682064e-02,  3.66175523e-01, -1.04097138e-01,
         1.17296417e+00,  1.68778774e+00, -1.45773797e+00,
        -8.98459190e-01, -1.25944706e+00,  9.48015916e-01,
        -8.62662186e-01,  3.95811403e+00, -6.13308070e-01,
        -7.17740563e-01,  1.08347268e+00, -1.45773797e+00],
       [ 1.21321465e+00,  9.24114764e-01, -2.26156419e-02,
        -1.07333816e+00, -1.08428595e+00, -1.45773797e+00,
        -8.98459190e-01, -1.25944706e+00, -1.05483461e+00,
         1.15920231e+00, -2.52645576e-01,  1.63050194e+00,
        -7.17740563e-01,  1.08347268e+00,  6.85994341e-01],
       [ 1.70381734e+00,  8.31124890e-01,  4.39112835e-01,
        -7.73831185e-01,  7.39667936e-02, -1.45773797e+00,
         1.11301661e+00,  7.93999233e-01, -1.05483461e+00,
         1.15920231e+00, -2.52645576e-01,  1.63050194e+00,
         1.39326109e+00,  1.08347268e+00,  6.85994341e-01],
       [-1.82852200e+00, -1.40063207e+00, -1.05471459e+00,
        -9.23584673e-01, -5.26172872e-01, -1.45773797

In [13]:
from sklearn.svm import SVR

In [14]:
regressor=SVR(kernel="rbf",C=3000)

In [15]:
regressor.fit(x_train,y_train)

C:\Users\Admin\anaconda3\envs\AIcoures\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=3000)

In [16]:
regressor.intercept_

array([266171.47570069])

In [17]:
regressor.n_support_

array([150])

In [18]:
regressor.support_

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [26]:
y_pred=regressor.predict(x_test)
y_pred=y_pred.reshape(65,1)

In [27]:
y_test

salary
198  265000.0
37   320000.0
89   210000.0
168  265000.0
171  290000.0
..        ...
157  300000.0
8    231000.0
40   287000.0
129  250000.0
13   218000.0

[65 rows x 1 columns]

In [28]:
residuals = y_test - y_pred
residuals

salary
198  -1269.203304
37   62118.261982
89  -53860.482181
168    540.915914
171  17327.775035
..            ...
157  32155.647757
8   -42147.067843
40   21589.533067
129 -26366.623767
13  -49822.800234

[65 rows x 1 columns]

In [31]:
import numpy as np
rss = np.sum(residuals**2)
rss

salary    1.017036e+11
dtype: float64

In [32]:
print("Residual Sum of Squares (RSS):", rss)

Residual Sum of Squares (RSS): salary    1.017036e+11
dtype: float64
